// Code generated by protoc-gen-validator. DO NOT EDIT.
// versions:
// 	protoc-gen-validator v0.1.1
// source: cart.proto

package cart

import (
	bytes "bytes"
	fmt "fmt"
	reflect "reflect"
	regexp "regexp"
	strings "strings"
	time "time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (m *CartItem) Validate() error {
	return nil
}

func (m *AddItemReq) Validate() error {
	return nil
}

func (m *AddItemResp) Validate() error {
	return nil
}

func (m *EmptyCartReq) Validate() error {
	return nil
}

func (m *GetCartReq) Validate() error {
	return nil
}

func (m *GetCartResp) Validate() error {
	return nil
}

func (m *Cart) Validate() error {
	return nil
}

func (m *EmptyCartResp) Validate() error {
	return nil
}
