// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	cart "github.com/Cui-Guo-crushed-his-team/CuiGuoMall/app/gateway/biz/router/cart"
	checkout "github.com/Cui-Guo-crushed-his-team/CuiGuoMall/app/gateway/biz/router/checkout"
	order "github.com/Cui-Guo-crushed-his-team/CuiGuoMall/app/gateway/biz/router/order"
	product "github.com/Cui-Guo-crushed-his-team/CuiGuoMall/app/gateway/biz/router/product"
	user "github.com/Cui-Guo-crushed-his-team/CuiGuoMall/app/gateway/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	user.Register(r)

	product.Register(r)

	order.Register(r)

	checkout.Register(r)

	cart.Register(r)
}
