// Code generated by protoc-gen-validator. DO NOT EDIT.
// versions:
// 	protoc-gen-validator v0.1.1
// source: checkout.proto

package checkout

import (
	bytes "bytes"
	fmt "fmt"
	reflect "reflect"
	regexp "regexp"
	strings "strings"
	time "time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (m *Address) Validate() error {
	return nil
}

func (m *CheckoutReq) Validate() error {
	if m.GetUserId() <= uint32(0) {
		return fmt.Errorf("field user_id gt rule failed, current value: %v", m.GetUserId())
	}
	return nil
}

func (m *CheckoutResp) Validate() error {
	return nil
}
