// Code generated by protoc-gen-validator. DO NOT EDIT.
// versions:
// 	protoc-gen-validator v0.1.1
// source: payment.proto

package payment

import (
	bytes "bytes"
	fmt "fmt"
	reflect "reflect"
	regexp "regexp"
	strings "strings"
	time "time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (m *PrepayReq) Validate() error {
	return nil
}

func (m *PrepayResp) Validate() error {
	return nil
}

func (m *RepayReq) Validate() error {
	return nil
}

func (m *RepayResp) Validate() error {
	return nil
}

func (m *FinishReq) Validate() error {
	return nil
}

func (m *FinishResp) Validate() error {
	return nil
}

func (m *GetByOutTradeNoReq) Validate() error {
	return nil
}

func (m *GetByOutTradeNoResp) Validate() error {
	return nil
}
