// Code generated by protoc-gen-validator. DO NOT EDIT.
// versions:
// 	protoc-gen-validator v0.1.1
// source: product.proto

package product

import (
	bytes "bytes"
	fmt "fmt"
	reflect "reflect"
	regexp "regexp"
	strings "strings"
	time "time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (m *ListProductsReq) Validate() error {
	return nil
}

func (m *Product) Validate() error {
	return nil
}

func (m *ListProductsResp) Validate() error {
	return nil
}

func (m *GetProductReq) Validate() error {
	return nil
}

func (m *GetProductResp) Validate() error {
	return nil
}

func (m *SearchProductsReq) Validate() error {
	return nil
}

func (m *SearchProductsResp) Validate() error {
	return nil
}
