// Code generated by protoc-gen-validator. DO NOT EDIT.
// versions:
// 	protoc-gen-validator v0.1.1
// source: order.proto

package order

import (
	bytes "bytes"
	fmt "fmt"
	reflect "reflect"
	regexp "regexp"
	strings "strings"
	time "time"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
	_ = (*bytes.Buffer)(nil)
	_ = (*strings.Builder)(nil)
	_ = reflect.Type(nil)
	_ = (*regexp.Regexp)(nil)
	_ = time.Nanosecond
)

func (m *Address) Validate() error {
	return nil
}

func (m *PlaceOrderReq) Validate() error {
	return nil
}

func (m *OrderItem) Validate() error {
	return nil
}

func (m *OrderResult) Validate() error {
	return nil
}

func (m *PlaceOrderResp) Validate() error {
	return nil
}

func (m *ListOrderReq) Validate() error {
	return nil
}

func (m *Order) Validate() error {
	return nil
}

func (m *ListOrderResp) Validate() error {
	return nil
}

func (m *MarkOrderPaidReq) Validate() error {
	return nil
}

func (m *MarkOrderPaidResp) Validate() error {
	return nil
}
